### ISSUE TITLE
Only supports .NET Framework 4.8

### ISSUE THREAD

**Issue by BillZulu** [cjvandyk/Quix#5]
Extensions.dll supports only 4.8.  Can you support more frameworks?

**Comment by cjvandyk** [comment]
Certainly!

**Comment by cjvandyk** [comment]
Hey Bill.  I've moved Extensions off to it's own repo.  I'm going to close this issue here.  If you'd kindly open it on the new repo so we can keep everything together, that would be much appreciated.
https://github.com/cjvandyk/Extensions
